### ISSUE TITLE
Files longer than 24 hours are not handled correctly

### ISSUE THREAD

**Issue by dm413** [cmxl/FFmpeg.NET#10]
I am processing audio files that are 6 days long. When I call `GetMetaDataAsync`, the duration is returned as zero. Also I do not get `Progress` events after 24 hours of audio have been processed.

This happens because the code uses `TimeSpan.TryParse` to parse the duration string that is output by ffmpeg. `TimeSpan.TryParse` does not handle hours that are greater than 23 (it expects days). Ffmpeg however produces a duration in `h:mm:ss.fff` format where the hours field can grow as large as necessary.

**Comment by cmxl** [comment]
Hi @dm413 and thanks for your contribution!
I'd like to merge your pullrequest, but I feel a bit unsure as long as there is no test for this function.
Do you mind adding one?

**Comment by dm413** [comment]
Added two tests, one for GetMetadataAsync and one for Progress events.  I'm not experienced with xunit tests; let me know if there are problems.

One issue was creating a file with > 24 hours duration to test with. I didn't want to put a large (175 MB) file into the repo, so the test program creates the test file at run time, by copying the SampleAudio file many times until the file is about 31 hours long . This means the first time you run the test it takes 10 to 20 seconds to create the test audio file.

**Comment by cmxl** [comment]
Thank you!
I will look into it after work ;)

**Comment by cmxl** [comment]
thanks again @dm413!
tests were also absolutely fine :)
