### ISSUE TITLE
Get converting progress

### ISSUE THREAD

**Issue by DarkEyeDragon** [cmxl/FFmpeg.NET#16]
I am converting files from webm to mp3's and i can't quite figure out how to get the overall progress of the process to display in a progress bar.

I have subscribed to the progress event and thats about how far i got.
How would i properly get the overall progress?

**Comment by cmxl** [comment]
This is probably related to #12 which is currently in review.

**Comment by cmxl** [comment]
You could use `var metadata = await ffmpeg.GetMetaDataAsync(input);` to check for samplerate and duration of your input file.
Then check against some of those properties in the progress event:

    private static void OnProgress(object sender, ConversionProgressEventArgs e)
    {
        Console.WriteLine("[{0} => {1}]", e.Input.FileInfo.Name, e.Output?.FileInfo.Name);
        Console.WriteLine("Bitrate: {0}", e.Bitrate);
        Console.WriteLine("Fps: {0}", e.Fps);
        Console.WriteLine("Frame: {0}", e.Frame);
        Console.WriteLine("ProcessedDuration: {0}", e.ProcessedDuration);
        Console.WriteLine("Size: {0} kb", e.SizeKb);
        Console.WriteLine("TotalDuration: {0}\n", e.TotalDuration);
    }

You have to calculate your overall progress somehow yourself expecially when converting multiple files at once. `ConversionProgressEventArgs` will just parse ffmpeg's progress output.
