### ISSUE TITLE
Thumbnail size

### ISSUE THREAD

**Issue by arc95** [cmxl/FFmpeg.NET#17]
Hi @yagotome. Great library! Is it possible to set the thumbnail size when you call this?

```
var options = new ConversionOptions { Seek = TimeSpan.FromSeconds(15) };
await ffmpeg.GetThumbnailAsync(inputFile, outputFile, options);
```
Thanks.

**Comment by cmxl** [comment]
Hi @arc95!
There are already conversion parameters for your task, but (!) they are not considered in the `GetThumbNailAsync` function. :(

    var thumbNail = await ffmpeg.GetThumbnailAsync(output, thumbNailFile, new ConversionOptions {
        CustomHeight = 100,
        CustomWidth = 100,
        VideoSize = Enums.VideoSize.Custom,
        Seek = TimeSpan.FromSeconds(3)
    });

If you know all the ffmpeg parameters you can adjust `FFmpegArgumentBuilder.GetThumbnail(MediaFile inputFile, MediaFile outputFile, ConversionOptions conversionOptions)` and create a pull request.
I'd love to merge that one!

**Comment by cmxl** [comment]
Just implemented it myself.
Have fun with version 3.3.0 and thumbnail sizes/cropping/aspect ratios! :)
