### ISSUE TITLE
Output buffer not flushed

### ISSUE THREAD

**Issue by ronaldvdv** [cmxl/FFmpeg.NET#25]
When I'm using GetMetadataAsync, it turns out the output/error streams are not flushed before we mark the task as completed. In my case this means the library only receives the first FFmpeg result line, which just contains the header. The fix seems relatively easy - I added `process.WaitForExit();` in the `process.Exited += ...` handler which forces the streams to be flushed. Putting the call there should be safe since we know the process itself is already finished. I'll open a pull request for this issue too.

**Comment by cmxl** [comment]
should be resolved by the pull request.
i want to merge the audiochannel pr #30 and #31 before creating a new version though.
