### ISSUE TITLE
TotalDuration always show 00:00:00

### ISSUE THREAD

**Issue by puangpaka20** [cmxl/FFmpeg.NET#29]
hello i try follow up the code  with "Subscribe to events" tutorial everything fine only the "TotalDuration", While convert the video file it always show 00:00:00

**Comment by cmxl** [comment]
should be fixed by #23 
Next version will contain the PR

**Comment by cmxl** [comment]
The TotalDuration property is actually always set to TimeSpan.Zero.
I guess this was an oversight even before forking the mediatoolkit library.
But as a workaround the total duration can be retrieved by GetMetaDataAsync(...)

**Comment by puangpaka20** [comment]
very thank you for fix this.
