### ISSUE TITLE
Application completely freezes during a call GetMetaData on version 1.1.8 previous version works fine

### ISSUE THREAD

**Issue by openlisp** [cmxl/FFmpeg.NET#3]
try
            {
                var inputFile = new MediaFile(path);
                var ffmpeg = new FFmpeg.NET.Engine.FFmpeg();
                var data = ffmpeg.GetMetaData(inputFile);  /// here it is, no exception catched application just not continue indefinetelly
                duration =  data.Duration;
            } catch( Exception ex)
            {
                Debug.WriteLine(ex);
            }

**Comment by cmxl** [comment]
Hi openlisp,
I cannot reproduce the issue.
Can you please provide some more info?

Is your inputfile a valid file for ffmpeg? Have you tried it with the ffmpeg cli?
What type of application do you use this code in? some asynchronous stuff around?

**Comment by cmxl** [comment]
@openlisp can you run the metadatatests successfully?
https://github.com/cmxl/FFmpeg.NET/blob/6c2ab321757539b0057fcd9cfe04cb22ac2204cd/tests/FFmpeg.NET.Tests/MetadataTests.cs#L16
