### ISSUE TITLE
Is video merging currently supported?

### ISSUE THREAD

**Issue by feiyit** [cmxl/FFmpeg.NET#36]
If not, how do I need to expand?

**Comment by tifcty1** [comment]
I also faced this situation. How did you solve it ?

**Comment by cmxl** [comment]
This can currently be achieved via `ConversionOptions.ExtraArguments`.
You need to provide the arguments manually there which is not ideal.
For concatenation see https://stackoverflow.com/questions/7333232/how-to-concatenate-two-mp4-files-using-ffmpeg

If you want to help out I guess you need to add some more options to `ConversionOptions` and use them in `FFmpegArgumentBuilder`. Finally another function in `Engine` would be great which accepts multiple `MediaFile` inputs. Same as `Engine.ConvertAsync` but with a `List<MediaFile>` as input parameter.
