### ISSUE TITLE
.net 4.0 is not available

### ISSUE THREAD

**Issue by icodeing** [cmxl/FFmpeg.NET#37]
My project is developed by.net 4.0, now nuget cannot be used, install-package xffmpegnet-version 3.4.0 cannot be installed。

ERROR:
The severity code indicates that the project file line forbids display status

The warning failed to resolve the main reference "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51", Because it is the framework assemblies "System. Diagnostics. Tracing, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a" indirect dependencies, and in the frame of the current target failed to resolve the assembly. ". NETFramework, Version = v4.0 ". To resolve this issue, remove references to "netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51", Or the application of the goal to contain "System. Diagnostics. Tracing, Version = 4.0.0.0, Culture = neutral, PublicKeyToken = b03f5f7f11d50a3a" framework Version. FFmpegDemo

**Comment by Nightmare204** [comment]
Added support for .NET Framework 4.5
This should be available when #42 pull request is accepted

**Comment by cmxl** [comment]
I decided to only maintain netstandard2.1 as a minimum which means that this library won't be available for .net4.0
