### ISSUE TITLE
Dosn't have custom atribute

### ISSUE THREAD

**Issue by vnikopol** [cmxl/FFmpeg.NET#4]
Supports custom FFmpeg command line arguments - NO!

**Comment by cmxl** [comment]
thanks for pointing it out.
i have updated the readme, but i want to add this feature back in.

**Comment by cmxl** [comment]
it is now supported as of v2.1.0

**Comment by bernd87** [comment]
> 
> 
> it is now supported as of v2.1.0

i've no clue how to use them

**Comment by WaGi-Coding** [comment]
> 
> 
> > it is now supported as of v2.1.0
> 
> i've no clue how to use them

I am trying the same with ExecuteAsync("my ffmpeg arguments") but i can't see any effect when running it. It just jumps over it

**Comment by przemo1983** [comment]
Same for me. How to use the arguments?
