### ISSUE TITLE
Use hardware accelerated encoding (NVENC)

### ISSUE THREAD

**Issue by LukeD1994** [cmxl/FFmpeg.NET#40]
Is there a way to make use of NVENC with this wrapper without having to switch to executeasync.
I'm fond of being able to attach event handlers to report progress as this is running on a server for me. But without setting custom attributes using execute I can't see a way to switch to NVENC encoding.

Is this possible?

**Comment by Nightmare204** [comment]
Hi Luke, I added some convertion Options in order to use HWAcc parameter and VideoEncoder parameter selection. 
This should be available when #42  pull request is accepted

**Comment by cmxl** [comment]
PR is merged v5 coming soon
