### ISSUE TITLE
Is FFmpeg.NET library support linux server?

### ISSUE THREAD

**Issue by MakeshR1981** [cmxl/FFmpeg.NET#41]
I want to convert wave file to 128Kbps, i can add new enum in AudioSampleRate as Hz4000, so that it will compress the file size and convert it to 128Kbs, but my question is this library support in Linux server.

**Comment by cmxl** [comment]
I just tested it with a simple console application on my raspberry pi with raspbian os.

I installed ffmpeg via `apt-get install ffmpeg`
`ffmpeg` was then already added to the `PATH`.
Afterwards instantiate the engine via:
```c#
var engine = new Engine("ffmpeg");
```
Worked perfectly on my little raspy :)
