### ISSUE TITLE
只有16：9 没有9比16吗

### ISSUE THREAD

**Issue by luoyigit** [cmxl/FFmpeg.NET#47]

**Comment by chadzhao** [comment]
This lib may be limited sometime, if you didn't find a way to do as 9:16, you can try my fork lib [FFmpegLite.NET](https://github.com/chadzhao/FFmpegLite.NET), which can extend by extra arguments.

---------- Translate To CN -- 
这个类库比较局限，如果你没找到可以设置9:16比例的地方，你可以试试我的库，可以自定义参数如果没达到你的需求。

**Comment by cmxl** [comment]
Extra arguments will be available in the next nuget package version v5
