### ISSUE TITLE
GetMetaDataAsync wont return frame size on video taken with iphone

### ISSUE THREAD

**Issue by Ivan-Zlatevski** [cmxl/FFmpeg.NET#48]
As it's shown on the image i can't seem to read the frame size of the video taken with iphone, i have no issues with other videos.
![image](https://user-images.githubusercontent.com/69164302/100349276-7feba580-2fe8-11eb-9132-38dba59fd910.png)
Here is the ffmpeg output for that video:
![image](https://user-images.githubusercontent.com/69164302/100350229-d7d6dc00-2fe9-11eb-90aa-d3331a87c350.png)

**Comment by cmxl** [comment]
This was due to a wrong Regex in `RegexEngine` and is now solved in `master`
