### ISSUE TITLE
Add support for input as URL

### ISSUE THREAD

**Issue by trinvh** [cmxl/FFmpeg.NET#60]
Currently the library does support for only local file. Please add new method `ConvertAsync` that accepts URL as string.

**Comment by cmxl** [comment]
You could actually implement your own `IArgument` class and make the argument for ffmpeg a url.
As far as I know `ffmpeg -i https://some.video.mp4 result.mp4` would work.

It would look something like this:
```csharp
public class UrlInput : IInputArgument
{
    public UrlInput(Uri uri)
    {
        Argument = uri.ToString();
    }

    public string Argument { get; }
    public MetaData MetaData { get; set; }
}
```
