### ISSUE TITLE
NETFramework 4.6.1Unable to install

### ISSUE THREAD

**Issue by shushu789** [cmxl/FFmpeg.NET#61]
NET Framework 4.6.1Unable to install
Severity Code Description Item File Line Prohibited display status
Error The package "xFFmpeg.NET 7.0.1" could not be installed. You are trying to install this package into a project whose target is ".NETFramework, Version=v4.6.1", but the package does not contain any assembly references or content files that are compatible with the framework. For more information, please contact the package author.

**Comment by cmxl** [comment]
The TargetFramework is currently `net6.0` and therefore cannot be used with net461.
Others have already mentioned to use netstandard which would possibly allow you to use it with net461.
