### ISSUE TITLE
Is it possible to specify a max filesize limit in ConversionOptions?

### ISSUE THREAD

**Issue by jmarkman** [cmxl/FFmpeg.NET#63]
When specifying conversion options, FFmpeg.NET allows me to do something like the following:

```csharp
var conversionOptions = new ConversionOptions()
{
    AudioBitRate = Encoding.AudioBitrate,
    RemoveAudio = Encoding.EnableAudio,
    VideoBitRate = Encoding.VideoBitrate,
    VideoFormat = FFmpeg.NET.Enums.VideoFormat.webm,
    VideoSize = FFmpeg.NET.Enums.VideoSize.Custom
};
```
My assumption is that the `VideoSize` property is what controls how big or small the output file's size will be, as there's no docstring specifying the behavior. There's an enum for `VideoSize` that allows us to declare a custom size, but I don't know how I can specify it outside of providing it via `ExtraArguments`.

**Comment by cmxl** [comment]
There is a `CustomHeight` and `CustomWidth` property on `ConversionOptions`:
https://github.com/cmxl/FFmpeg.NET/blob/d0fb5142adfb8bdab1da65ab9fd1e79130d4b25c/src/FFmpeg.NET/ConversionOptions.cs#L135
https://github.com/cmxl/FFmpeg.NET/blob/d0fb5142adfb8bdab1da65ab9fd1e79130d4b25c/src/FFmpeg.NET/ConversionOptions.cs#L140

There are still many parts that need thorough documentation. Help is always appreciated!
