### ISSUE TITLE
Code update needed

### ISSUE THREAD

**Issue by Th-69** [cmxl/FFmpeg.NET#71]
You should update the code samples on the main page, because _MediaFile_ is now an abstract class  and can't be used directly.
```
var inputFile = new InputFile (@"C:\Path\To_Video.flv");
var outputFile = new OutputFile (@"C:\Path\To_Save_Image.jpg");
```
etc.

**Comment by Sttony-Shi** [comment]
I also think that looking at examples bothers me a lot.
