### ISSUE TITLE
Missing progress events

### ISSUE THREAD

**Issue by dm413** [cmxl/FFmpeg.NET#9]
I am writing a program to split a large audio file into smaller segments. I use the `ExecuteAsync` method and pass the `-f segment` and `-segment_time `options in the arguments parameter. This works, but I do not get any `Progress` events from ffmpeg.net.

The problem is that ffmpeg produces a minimal progress data line when using the segment option. In this configuration, the progress data lines look like this:

`	size=N/A time=00:11:00.11 bitrate=N/A speed=1.32e+03x
`

The "N/A" values confuse the parser in ffmpeg.net, and it does not see these as valid progress lines.

I am able to work around the problem by subscribing to the `Data` event and performing my own parsing to check for progress lines. But it would be nice if ffmpeg could handle these lines and produce `Progress` events itself.

**Comment by cmxl** [comment]
Ah now I see!
Would be great to add a test with those parameters just to make sure OnProgress will now always trigger, no matter if size/bitrate are there or not.
I'd love to merge this one afterwards
